# Generated by Django 4.0 on 2021-12-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
