# Generated by Django 4.0 on 2021-12-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_med_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
