# Generated by Django 4.0 on 2022-01-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_med_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
