# Generated by Django 4.0 on 2022-01-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_med_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='name',
            new_name='name_of_medicine',
        ),
    ]
