# Generated by Django 4.0 on 2022-01-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_name_med_name_of_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='name_of_medicine',
            new_name='medicine',
        ),
    ]
