# Generated by Django 4.0 on 2022-01-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_name_of_medicine_med_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='med',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.med'),
            preserve_default=False,
        ),
    ]
