# Generated by Django 4.0 on 2022-01-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_log_med'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='total',
            new_name='total_doses',
        ),
    ]
