# Generated by Django 4.0 on 2022-01-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_total_med_total_doses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='medicine',
            new_name='name',
        ),
    ]
