# Generated by Django 4.0 on 2022-01-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_medicine_med_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='name',
            new_name='name_of_Med',
        ),
    ]
