# Generated by Django 4.0 on 2022-01-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_name_med_name_of_med'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='name_of_Med',
            new_name='name',
        ),
    ]
