# Generated by Django 4.0 on 2022-01-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_name_of_med_med_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(verbose_name='Date Given'),
        ),
        migrations.AlterField(
            model_name='med',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Medicine'),
        ),
    ]
