# Generated by Django 4.0 on 2022-01-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_log_med_med_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med',
            name='log',
        ),
        migrations.AddField(
            model_name='log',
            name='med',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.med'),
            preserve_default=False,
        ),
    ]
